// ============================================================================
//   Ver  :| Author                    :| Mod. Date :| Changes Made:
//   V1.1 :| Alexandra Du              :| 06/01/2016:| Added Verilog file
// ============================================================================


//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

`define ENABLE_ADC_CLOCK
`define ENABLE_CLOCK1
`define ENABLE_CLOCK2
`define ENABLE_SDRAM
`define ENABLE_HEX0
`define ENABLE_HEX1
`define ENABLE_HEX2
`define ENABLE_HEX3
`define ENABLE_HEX4
`define ENABLE_HEX5
`define ENABLE_KEY
`define ENABLE_LED
`define ENABLE_SW
`define ENABLE_VGA
`define ENABLE_ACCELEROMETER
`define ENABLE_ARDUINO
`define ENABLE_GPIO

module DE10_LITE_Golden_Top(

    //////////// ADC CLOCK: 3.3-V LVTTL //////////
`ifdef ENABLE_ADC_CLOCK
    input  logic        ADC_CLK_10,
`endif
    //////////// CLOCK 1: 3.3-V LVTTL //////////
`ifdef ENABLE_CLOCK1
    input  logic        MAX10_CLK1_50,
`endif
    //////////// CLOCK 2: 3.3-V LVTTL //////////
`ifdef ENABLE_CLOCK2
    input  logic        MAX10_CLK2_50,
`endif

    //////////// SDRAM: 3.3-V LVTTL //////////
`ifdef ENABLE_SDRAM
    output logic [12:0] DRAM_ADDR,
    output logic [1:0]  DRAM_BA,
    output logic        DRAM_CAS_N,
    output logic        DRAM_CKE,
    output logic        DRAM_CLK,
    output logic        DRAM_CS_N,
    inout  wire  [15:0] DRAM_DQ,
    output logic        DRAM_LDQM,
    output logic        DRAM_RAS_N,
    output logic        DRAM_UDQM,
    output logic        DRAM_WE_N,
`endif

    //////////// SEG7: 3.3-V LVTTL //////////
`ifdef ENABLE_HEX0
    output logic [7:0]  HEX0,
`endif
`ifdef ENABLE_HEX1
    output logic [7:0]  HEX1,
`endif
`ifdef ENABLE_HEX2
    output logic [7:0]  HEX2,
`endif
`ifdef ENABLE_HEX3
    output logic [7:0]  HEX3,
`endif
`ifdef ENABLE_HEX4
    output logic [7:0]  HEX4,
`endif
`ifdef ENABLE_HEX5
    output logic [7:0]  HEX5,
`endif

    //////////// KEY: 3.3 V SCHMITT TRIGGER //////////
`ifdef ENABLE_KEY
    input  logic [1:0]  KEY,
`endif

    //////////// LED: 3.3-V LVTTL //////////
`ifdef ENABLE_LED
    output logic [9:0]  LEDR,
`endif

    //////////// SW: 3.3-V LVTTL //////////
`ifdef ENABLE_SW
    input  logic [9:0]  SW,
`endif

    //////////// VGA: 3.3-V LVTTL //////////
`ifdef ENABLE_VGA
    output logic [3:0]  VGA_B,
    output logic [3:0]  VGA_G,
    output logic        VGA_HS,
    output logic [3:0]  VGA_R,
    output logic        VGA_VS,
`endif

    //////////// Accelerometer: 3.3-V LVTTL //////////
`ifdef ENABLE_ACCELEROMETER
    output logic        GSENSOR_CS_N,
    input  logic [2:1]  GSENSOR_INT,
    output logic        GSENSOR_SCLK,
    inout  wire         GSENSOR_SDI,
    inout  wire         GSENSOR_SDO,
`endif

    //////////// Arduino: 3.3-V LVTTL //////////
`ifdef ENABLE_ARDUINO
    inout  wire  [15:0] ARDUINO_IO,
    inout  wire         ARDUINO_RESET_N,
`endif

    //////////// GPIO, GPIO connect to GPIO Default: 3.3-V LVTTL //////////
`ifdef ENABLE_GPIO
    inout  wire  [35:0] GPIO
`endif
);


//=======================================================
//  REG/WIRE declarations
//=======================================================

   logic                         pll_rst;
   logic                         pll_locked;
   logic                         rst_ni;
   logic                         sys_clk;
   logic                         spi_clk;
   logic                         spi_req;
   logic                         spi_rw_ni;
   logic [5:0]                   spi_addr;
   logic [7:0]                   spi_wr_data;
   logic                         spi_ack;
   logic [7:0]                   spi_rd_data;
   logic                         spi_cs_no;
   logic                         spi_clk_o;
   logic                         spi_data_o;
   logic                         spi_data_i;
   logic                         spi_oe_o;
   logic                         init_done;
   logic signed [9:0]            accel_x;
   logic signed [9:0]            accel_y;
   logic                         row_o;
   logic [$clog2(6)-1:0]         col_o;
   logic [6-1:0][7:0]            seg_active_high;
   logic [6-1:0][7:0]            seg_o;


//=======================================================
//  Structural coding
//=======================================================

   assign pll_rst = ~KEY[0];
   assign rst_ni  = KEY[0] & pll_locked;

   assign GSENSOR_SDI  = spi_oe_o ? spi_data_o : 1'bz;
   assign spi_data_i   = GSENSOR_SDI;
   assign GSENSOR_CS_N = spi_cs_no;
   assign GSENSOR_SCLK = spi_clk_o;

`ifdef ENABLE_HEX0
   assign HEX0 = seg_o[0];
`endif
`ifdef ENABLE_HEX1
   assign HEX1 = seg_o[1];
`endif
`ifdef ENABLE_HEX2
   assign HEX2 = seg_o[2];
`endif
`ifdef ENABLE_HEX3
   assign HEX3 = seg_o[3];
`endif
`ifdef ENABLE_HEX4
   assign HEX4 = seg_o[4];
`endif
`ifdef ENABLE_HEX5
   assign HEX5 = seg_o[5];
`endif

`ifdef ENABLE_LED
   assign LEDR = '0;
`endif

   adxl345_controller u_adxl345_controller (
                                            .clk_i      (sys_clk),
                                            .rst_ni     (rst_ni),
                                            .ack_i      (spi_ack),
                                            .rd_data_i  (spi_rd_data),
                                            .req_o      (spi_req),
                                            .rw_ni_o    (spi_rw_ni),
                                            .addr_o     (spi_addr),
                                            .wr_data_o  (spi_wr_data),
                                            .init_done_o(init_done),
                                            .accel_x_o  (accel_x),
                                            .accel_y_o  (accel_y)
                                            );

   position_ctrl #(
                   .DISPLAYS (6),
                   .X_RAW_PER_COLUMN (64)
                   ) u_position_ctrl (
                                      .accel_x_i (accel_x),
                                      .accel_y_i (accel_y),
                                      .row_o     (row_o),
                                      .col_o     (col_o)
                                      );

   display_map #(
                 .DISPLAYS (6)
                 ) u_display_map (
                                  .row_i (row_o),
                                  .col_i (col_o),
                                  .out_o (seg_active_high)
                                  );

   assign seg_o = ~seg_active_high;

   alt_pll u_alt_pll (
                      .areset (pll_rst),
                      .inclk0 (MAX10_CLK1_50),
                      .c0     (sys_clk),
                      .c1     (spi_clk),
                      .locked (pll_locked)
                      );

   spi_phy u_spi_phy (
                      .rst_ni     (rst_ni),
                      .clk_i      (sys_clk),
                      .spi_clk_i  (spi_clk),
                      .req_i      (spi_req),
                      .rw_ni      (spi_rw_ni),
                      .addr_i     (spi_addr),
                      .wr_data_i  (spi_wr_data),
                      .ack_o      (spi_ack),
                      .rd_data_o  (spi_rd_data),
                      .spi_cs_no  (spi_cs_no),
                      .spi_clk_o  (spi_clk_o),
                      .spi_data_o (spi_data_o),
                      .spi_data_i (spi_data_i),
                      .spi_oe_o   (spi_oe_o)
                      );

`ifdef ENABLE_SDRAM
   assign DRAM_ADDR  = '0;
   assign DRAM_BA    = '0;
   assign DRAM_CAS_N = 1'b1;
   assign DRAM_CKE   = 1'b0;
   assign DRAM_CLK   = 1'b0;
   assign DRAM_CS_N  = 1'b1;
   assign DRAM_LDQM  = 1'b0;
   assign DRAM_RAS_N = 1'b1;
   assign DRAM_UDQM  = 1'b0;
   assign DRAM_WE_N  = 1'b1;
`endif

`ifdef ENABLE_VGA
   assign VGA_B  = '0;
   assign VGA_G  = '0;
   assign VGA_HS = 1'b0;
   assign VGA_R  = '0;
   assign VGA_VS = 1'b0;
`endif

`ifdef ENABLE_ARDUINO
   assign ARDUINO_IO      = 'z;
   assign ARDUINO_RESET_N = 1'bz;
`endif

`ifdef ENABLE_GPIO
   assign GPIO = 'z;
`endif

endmodule : DE10_LITE_Golden_Top
