#!/usr/bin/env sh

# SPDX-License-Identifier: CC0-1.0
# Original-Author: Dan NICULA <dan.nicula@unitbv.ro>
# Fork_Author: Elias-Robert BAJCSI <elias.bajcsi@student.unitbv.ro>
# Timestamp: 2025-03-14 02:13 AM GMT+2
#
# This POSIX-compliant shell script is meant to be used for cleaning up
# temporary artifact files generated by Intel's ModelSim HDL software.
#
# This fork is a migration from the MS-Windows-only Batch script made by the
# previous author, Dan NICULA.
#
# The previous license cannot be yet determined, but it's assumed that it falls
# under the terms of FAIR USE, therefore this script is licensed under the
# public domain rules, unless specified otherwise in the future, including this
# version.

BASE_DIR="./debug/sim/"
TO_DEL="sim.tcl modelsim.ini vsim.wlf \
       transcript vish_stacktrace.vstf tcl_stacktrace.txt \
       vlog.opt work output_data/*.* input_data/*.bak"

for p in ${TO_DEL}; do
    set -- $BASE_DIR${p} # Expand to pos params
    for f in "$@"; do    # Run prev expansion
        if [ -e "${f}" ]; then
            rm -rf "${f}"
        fi
    done
done
