#+title: Seminar Psiho-Pedagogie - 09 Nov 2023

* Chestionare
1. Chestionar pentru preferinta stilului personal de invatat
   1. Când întâlniți o persoană necunoscută, ce vă frapează prima oară la ea?
      a) Înfățișarea sau modul cum se îmbracă;
      b) Felul cum vorbește, ceea ce spune sau cuvintele sale;
      c) Ceea ce simțiți pentru ea;
      d) *Modul cum se comportă persoana sau acțiunile ei.*
   2. La câteva zile după ce ați cunoscut o persoană, ce anume vă amintiți cel mai bine despre ea?
      a) Chipul;
      b) Numele;
      c) *Cum v-ați simțit alături de ea, chiar dacă i-ați uitat numele sau chipul;*
      d) Ceea ce ați făcut împreună cu ea, chiar dacă i-ați uitat numele și chipul
   3. Când intrați într-o cameră în care n-ați mai fost niciodată, ce vă atrage cel mai mult atenția?
      a) *Felul cum arată interiorul;*
      b) Sunetele sau discuțiile dinăuntru;
      c) Cât de confortabil vă simțiți, emoțional sau fizic, în cameră;
      d) Ce activități au loc înăuntru și ce anume puteți face acolo
   4. Când învățați ceva nou, cum ar trebui să se procedeze?
      a) Profesorul vă dă să citiți ceva scris pe hârtie sau pe tablă și vă arată cărți, imagini, grafice, hărți, desene, obiecte, dar nu au loc discuții și nici nu se scrie nimic;
      b) Profesorul explică totul verbal și vă permite să discutați subiectul și să puneți întrebări, dar nu vă ofera nimc să priviți, să citiți, să scrieți sau să faceți;
      c) Profesorul vă permite să scrieți sau să desenați informațiile, să atingeți în mod direct materialele, sau să faceți ceva cu mâinile;
      d) *Profesorul vă permite să vă ridicați din bancă pentru a executa proiecte, simulări, experiențe, să jucați jocuri, să interpretați personaje și situații din viața reală, să explorați, să faceți descoperiri ori activități care vă îngăduie să vă deplasați, în scopul învățării.*
   5. Când îi învățați pe alții, cum procedati?
      a) Le oferiți ceva la care să privească – un obiect, o imagine sau un grafic -, fără explicații verbale sau discuții; sau un nivel redus al acestora;
      b) Le explicați verbal, fără a le oferi materiale vizuale;
      c) Desenați, scrieți sau vă folosiți mâinile pentru a le explica;
      d) *Le demonstrați o acțiune în mod practic și le cereți s-o facă împreună cu dumneavoastră.*
   6. Ce tip de cărți preferați să citiți?
      a) Cărți ce conțin descrieri menite să vă ajute să vizualizați cele ce se întâmplă;
      b) Cărți conținând informații exacte, istorie sau cu multe dialoguri;
      c) Cărți despre sentimentele și emoțiile personajelor, despre sentimente și relații, sau despre perfecționarea minții și a corpului;
      d) *Cărți cu multă acțiune sau cărți ce vă ajută să vă perfecționați într-un sport, într-un hobby sau să vă dezvoltați un anumit talent.*
   7. Ce preferați să faceți în timpul liber?
      a) Să citiți o carte sau să răsfoiți o revistă;
      b) Să ascultați un talk-show radiofonic, să ascultați sau să interpretați muzică;
      c) Să scrieți, să desenați, să dactilografiați ori să faceți ceva cu mâinile;
      d) *Să faceți sport, să construiți ceva sau să jucați un joc folosindu-vă de întregul corp.*
   8. Care dintre următoarele variante descrie modul în care puteți citi sau studia cel mai bine?
      a) Puteți studia în prezența muzicii, a zgomotelor sau unor conversații, deoarece le eliminați mintal;
      b) Nu puteți studia în prezența muzicii, a zgomotelor sau a unor conversații, deoarece nu le puteți elimina mintal;
      c) Trebuie să vă simțiți confortabil, relaxat și puteți lucra cu sau fără muzică, dar vă distrag sentimentele negative ale altora;
      d) *Trebuie să vă simțiți confortabil, relaxat și puteți lucra cu sau fără muzică, dar vă distrag activitățile sau mișcările din odaie.*
   9. Când vorbiți cu cineva, în ce direcție vi se deplasează ochii? (Puteți ruga pe cineva să vă observe, pentru a vă ajuta să răspundeți la înterbare)
      a) Priviți direct chipul interlocutorului și doriți ca și el să vă privească;
      b) *Priviți interlocutorul doar scurt timp, apoi ochii vi se deplasează dintr-o parte în cealaltă, la stânga și la dreapta;*
      c) Priviți interlocutorul doar scurt timp, pentru a-i vedea expresia apoi vă feriți ochii;
      d) Priviți arareori interlocutorul; în majoritatea timpului vă uitați în jos sau lateral dar dacă există activitate sau mișcări, priviți în direcția respectivă.
   10. Care dintre urmatoarele atitudini vă descrie cel mai bine?
       a) Oriunde v-ați afla remarcați culorile, formele, desenele, vă pricepeți la culori și la desene;
       b) Nu puteți suporta liniștea și, atunci când vi se pare că un loc este prea tăcut, fredonați, cântați, vorbiți tare sau deschideți radioul, televizorul, casetofonul etc., pentru a menține un stimul auditiv în ambient;
       c) Sunteți sensibil față de sentimentele oamenilor, propriile dumneavoastră sentimente pot fi rănite cu ușurință, nu vă puteți concentra când alții nu vă plac, și – pentru a lucra – aveți nevoie să vă simțiți iubit și acceptat;
       d) *Vă vine greu să stați nemișcat pe locul dumneavoastră, trebuie să vă mișcați mult; dacă nu vă puteți părăsi scaunul, vă foiți, vă mișcați mult picioarele sau bateți tactul cu vârful picioarelor în podea.*
   11. Care dintre următoarele atitudini vă descrie cel mai bine?
       a) Remarcați dacă îmbrăcămintea oamenilor nu este asortată sau dacă părul le este răvășit și adesea doriți să rectificați asemenea situații;
       b) Vă deranjează când cineva nu vorbește corect și sunteți sensibil față de anumite sunete, precum picuratul robinetelor sau zgomotul aparatelor casnice;
       c) Lăcrimați la episoadele triste din filme sau cărți;
       d) *Vă foiți și nu vă găsiți locul când sunteți silit să rămaneți nemișcat și nu puteți sta prea mult timp în același loc*
   12. Ce anume vă deranjează cel mai mult?
       a) Un loc dezordonat;
       b) Un loc prea tăcut;
       c) Un loc inconfortabil din punct de vedere fizic sau emoțional;
       d) *Un loc în care nu se permit activități sau care nu oferă suficient spațiu de mișcare.*
   13. Ce vă deranjează cel mai mult atunci când cineva predă un subiect?
       a) *Să ascultați o expunere neînsoțită de materiale vizuale;*
       b) Să fiți nevoit să citiți în tăcere, fără explicații verbale sau discuții;
       c) Să nu vi se îngăduie să desenați, să măzgăliți, să atingeți ceva cu mâinile sau să faceți însemnări, chiar dacă nu le veți reciti niciodată;
       d) Să fiți nevoit să citiți și să ascultați fără a va putea clinti.
   14. Rememorați o amintire foarte fericită din viață. Petreceți câteva secunde căutând să vă amintiți cât mai multe detalii. După ce ați retrăit episodul, ce amintiri ies în evidență?
       a) Cele văzute – descrierile vizuale ale oamenilor, locurilor și obiectelor;
       b) Cele auzite – dialoguri și conversații, replicile dumneavoastră și sunetele din jur;
       c) *Senzațiile de pe piele și corp, precum și felul cum v-ați simtit, fizic și emoțional;*
       d) Acțiunile și activitățile întreprinse de dumneavoastră și mișcările corpului.
   15. Rememorați o vacanță sau o călătorie. Petreceți câteva secunde căutând să vă amintiți cât mai multe detalii. După ce ați retrăit episodul, ce amintiri ies în evidență?
       a) *Cele văzute – descrierile vizuale ale oamenilor, locurilor, obiectelor*
       b) Cele auzite – dialoguri și conversații, replicile dumneavoastră și sunetele din jur;
       c) Senzațiile de pe piele și corp, precum și felul cum v-ați simțit, fizic și emoțional;
       d) Acțiunile și activitățile întreprinse de dumneavoastră și mișcările corpului.
   16. Imaginați-vă că ați putea să vă petreceți tot timpul în unul din următoarele locuri, în care se desfășoară activități diferite. Unde v-ați simți cel mai confortabil?
       a) Un loc în care puteți să citiți; să priviți tablouri, opere de artă, hărți geografice, fotografii; să rezolvați puzzle-uri vizuale, de felul labirinturilor sau descoperirii fragmentelor lipsă dintr-un tablou; să jucați jocuri cu litere, de tip scrabble; să efectuați decorațiuni interioare etc;
       b) Un loc în care puteți asculta muzică, talk-show-uri radiofonice sau TV, ori știri; să cântați, vocal sau la un instrument; să jucați jocuri verbale, să participați la dezbateri; să citiți cu voce tare, să recitiți fragmente din piese sau filme etc;
       c) Un loc în care puteți desena, picta, sculpta sau crea obiecte artizanale; să scrieți sau să dactilografiați; să efectuați activități ce implică mâinile, așa cum sunt cântatul la un instrument, jucatul de șah, dame etc; să construiți machete;
       d) Un loc în care să faceți sport, să jucați jocuri cu mingea ori jocuri de acțiune, care implică mișcarea trupului sau să jucați în piese sau spectacole; să efectuați proiecte în care să vă deplasați constant; să efectuați experiențe sau să explorați și să descoperiți lucruri noi; să construiți sau să reparați diverse obiecte; să participați în activități de echipă cu caracter competitiv.
