#+title: Portofoliu seminar Modul de Pregătire a Personalului Didactic -- Nivel I
#+SUBTITLE: Facultatea de Inginerie Electrică și Știința Calculatoarelor (IESC)\\
#+SUBTITLE: Anul II -- 2024-2025\\
#+SUBTITLE: Semestrul I
#+AUTHOR: BAJCSI Elias-Robert
#+OPTIONS: toc:nil date:nil
#+LATEX_HEADER: \usepackage[a4paper,margin=1.75cm]{geometry}
#+LATEX_HEADER: \usepackage{titling} \setlength{\droptitle}{-2cm}
#+LATEX_HEADER: \usepackage{hyperref}
#+LATEX_HEADER: \hypersetup{breaklinks=true}
#+LATEX_HEADER: \sloppy
#+LATEX_HEADER: \usepackage{lastpage}
#+LATEX_HEADER: \usepackage{fancyhdr}
#+LATEX_HEADER: \usepackage{graphicx}
#+LATEX_HEADER: \pagestyle{fancy}
#+LATEX_HEADER: \fancyhf{} % Clear all default header/footer
#+LATEX_HEADER: \pretitle{
#+LATEX_HEADER: \includegraphics[width=4cm]{./assets/logo_ro-RO_peda.png}
#+LATEX_HEADER: \hfill \includegraphics[width=4cm]{./assets/logo_ro-RO.png}\Large\begin{center}\vspace{10em}\\}
#+LATEX_HEADER: \posttitle{\end{center}}
#+LATEX_HEADER: \cfoot{\thepage/\pageref{LastPage}}


\newpage

* [TMI] Ilustrarea, cu ajutorul unui exemplu (situație de învățare), a aplicării a două metode didactice relevante pentru domeniul de specialitate.
** Specializare: Informatică și TIC
** Situația de învățare
Lecția are ca scop învățarea utilizării software-ului de prezentare (MS PowerPoint | LibreOffice Impress | WPS | Google Slideshows) pentru a crea o prezentare despre un subiect de ales de elevi, precum "Squid Game sezonul 2". Elevii vor învăța să utilizeze cep puțin funcții de bază precum inserarea unui slide, introducerea de text și imagini, utilizarea tranzițiilor și animațiilor, dar la alegerea lor vor utiliza și alte efecte pentru exersarea creativitații.

*** Metoda demonstrației
- Aplicare: Profesorul începe lecția prin a demonstra utilizarea funcțiilor de bază din PowerPoint, folosind proiectorul.
- Exemplu concret:
  Profesorul creează un slide pe loc:
  - Titlul: Se adaugă titlul "Mașini clasice"
  - Diapozitive: Se creează diapozitive
  - Imagini: Se adaugă fotografii cu mașini clasice preluate din internet
  - Tranziție: Adaugă o tranziție simplă între slide-uri
Elevii urmăresc demonstrația și repetă instrucțiunile.

*** Învățarea în echipe
- Aplicare: Elevii lucrează în echipe de 2-3 persoane pentru a crea o prezentare despre un animal la alegere.
- Cerințe:
  - Diapozitivul 1: Titlul prezentării și numele participanților
  - Diapozitivul 2: O imagine a animalului ales și câteva informații
  - Diapozitive de mijloc: Exersarea creativității
  - Ante-ultimul diapozitiv: O concluzie și efecte de tranziție
  - Ultimul diapozitiv: Bibliografie selectivă
- Exemplu concret:
  O echipă alege subiectul "Anime-uri" și creează o prezentare care include:
  - Imagini cu anime
  - Text informativ despre anime-uri
  - Efecte de tranziție pentru fiecare slide
  - Animații de mișcare a imaginilor + textului

** Concluzie
La final, fiecare echipă își prezintă proiectul în fața clasei, în mai multe ore.
Cele două metode:
- Ajută elevii să înțeleagă funcțiile software-ului prin exemple vizuale
- Permite exersarea practică într-un context colaborativ
- Dezvoltă anumite competențe precum creativitatea, colaborareea și abilitățile de prezentare

\newpage
* [TME] Elaborarea unei probe de evaluare pentru o unitate de învățare la o disciplină de specialitate.
\vspace{2em}
\begin{center}
        \Large {Test de Evaluare Unitară 3}\\
        \vspace{.5em}
        \large {Informatică și TIC}
\end{center}

\noindent
NUME Prenume: $\rule{4cm}{0.4pt}$      \hfill      Nota: $\rule{.5cm}{0.4pt}$ ($\rule{3cm}{0.4pt}$) \\
Clasa: a V-a $\rule{.5cm}{0.4pt}$                          \hfill      *COPIAT(nota 2)* $\Box$ \\
Data susținerii: $\rule{3cm}{0.4pt}$ \\

\scriptsize
\noindent /Timpul de lucru este de 45 de minute.  Se acordă 20 de puncte din oficiu.  Se acordă nota 2 fraudei sau tentativei de fraudă.  Punctajul se împarte la 10.  Toate subiectele sunt obligatorii./\\

\normalsize

\noindent Creează un nou director denumit <An-Lună-Zi-Oră-NUME-Prenume> în care îți vei salva tot progresul acestei evaluări. După terminarea evaluării, vei arhiva acest director în format ZIP, cu aceeași denumire, păstrând ".zip" la sfârșit.  Apoi vei apăsa click-dreapta pe arhivă, vei da click-stânga pe proprietăți și vei raporta mărimea arhivei aici $\rule{4cm}{0.4pt}$, apoi vei copia arhiva pe unitatea de stocare atribuită de profesor.

** Subiectul I - Capătură de ecran
1. Închide sau ascunde toate ferestrele și realizează o captură de ecran.  În programul Microsoft Paint, lipește această captură de ecran \hfill *[10 p]*
2. După aceea, desenează o casă cu un acoperiș roșu, perete albastru (sau altă culoare dacă are o culoare asemănătoare cu fundalul), o grădiniță cu flori și două ferestre. \hfill *[20 p]*
3. NU UITA să salvezi imaginea în directorul tău. \hfill *[0 p]*

** Subiectul II - Comenzi principale
1. Deschide un browser și prin navigarea internetului, descarcă în folderul tău o imagine cu o familie formată din doi părinți și cel puțin doi copii. Duplică imaginea, adăugând OG la începutul numelui fișierului. Deschide imaginea fără "OG" în MS Paint. \hfill *[5 p]*
2. Selectează unul dintre copii și clonează-l o singură dată. \hfill *[10 p]*
3. Selectează cea mai mare persoană și micșoreaz-o aproximativ lafel cât cea mai mică persoană. *[10 p]*
4. NU UITA să salvezi imaginea în directorul tău. \hfill *[0 p]*

** Subiectul III - Prelucrarea culorilor
1. Deschide un browser și prin navigarea internetului, descarcă în folderul tău o imagine cu diferite culori. Duplică imaginea, adăugând OG la începutul numelui fișierului. Deschide imaginea fără "OG" în MS Paint.\hfill *[5 p]*
2. Schimbă culoarea unei flori cu o culoare diferită, prin folosirea funcției de umplere. \hfill *[10 p]*
3. Scrie numele tău prin folosirea funcției de adăugare a textului. Textul va îngroșat și subliniat, culoarea trebuie să difere de cea de fundal însă să nu fie negru, iar numele trebuie să fie suficient de mare/mic încât să fie vizibil în întregime. \hfill *[10 p]*
4. NU UITA să salvezi imaginea în directorul tău. \hfill *[0 p]*

\newpage

\vspace{2em}
\begin{center}
        \Large {Barem de corectare pentru Test de Evaluare Unitară 3}\\
        \vspace{.5em}
        \large {Informatică și TIC}
\end{center}
* Barem
** Subiectul I - Captură de ecran
- Realizarea capturii de ecran și lipirea în Microsoft Paint:
  - Captură de ecran realizată corect și lipită în Paint \hfill *[10 p]*
  - Captură de ecran lipsă sau greșită \hfill *[0 p]*
- Desenarea unei case în Microsoft Paint:
  - Acoperiș roșu \hfill *[5 p]*
  - Perete albastru (sau altă culoare potrivită) \hfill *[5 p]*
  - Grădiniță cu flori \hfill *[5 p]*
  - Două ferestre \hfill *[5 p]*

** Subiectul II - Comenzi principale
- Deschiderea unui browser și descărcarea unei imagini cu o familie:
  - Imagine descărcată corect \hfill *[5 p]*
  - Duplicarea imaginii cu „OG” în numele fișierului \hfill *[5 p]*
    - Editarea imaginii în Microsoft Paint dacă OG există:
      - Clonarea unui copil o singură dată: \hfill *[5 p]*
      - Micșorarea celei mai mari persoane la dimensiunea celei mai mici \hfill *[10 p]*

** Subiectul III - Prelucrarea culorilor
- Descărcarea unei imagini cu diferite culori:
  - Imagine descărcată corect \hfill *[5 p]*
  - Duplicarea imaginii cu „OG” în numele fișierului: \hfill *[5 p]*
    - Editarea imaginii în Microsoft Paint dacă OG există:
      - Schimbarea culorii unei flori: \hfill *[10 p]*
      - Adăugarea numelui utilizând funcția de text:
        - Textul este îngroșat și subliniat: \hfill *[5 p]*
        - Culoarea textului este diferită de fundal, dar nu negru: \hfill *[5 p]*
        - Numele este vizibil integral: \hfill *[5 p]*

* Bibliografie
- Stiluri de învăţare.docx
- Mijloace de învățământ.docx
- https://www.math.uaic.ro/~oanacon/depozit/Curs_8_StratII.pdf
- http://paradigme.euroeducation.ro/wp-content/uploads/2019/02/Metode-%C8%99i-procedee-folosite-%C3%AEn-predare.-Ghid-Metodologic.pdf
- https://manuale.edu.ro/manuale/Clasa%20a%20VI-a/Informatica%20si%20TIC/R1JVUCBFRElUT1JJQUwg/A1448.pdf
- https://manuale.edu.ro/manuale/Clasa%20a%20V-a/Informatica%20si%20TIC/Q0QgUFJFU1M/A1225.pdf
