// ============================================================================
//   Ver  :| Author					:| Mod. Date :| Changes Made:
//   V1.1 :| Alexandra Du			:| 06/01/2016:| Added Verilog file
// ============================================================================

//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================
 
`define ENABLE_ADC_CLOCK
`define ENABLE_CLOCK1
`define ENABLE_CLOCK2
`define ENABLE_SDRAM
`define ENABLE_HEX0
`define ENABLE_HEX1
`define ENABLE_HEX2
`define ENABLE_HEX3
`define ENABLE_HEX4
`define ENABLE_HEX5
`define ENABLE_KEY
`define ENABLE_LED
`define ENABLE_SW
`define ENABLE_VGA
`define ENABLE_ACCELEROMETER
`define ENABLE_ARDUINO
`define ENABLE_GPIO
 
module DE10_LITE_Golden_Top(
    
   	//////////// ADC CLOCK: 3.3-V LVTTL //////////
   `ifdef ENABLE_ADC_CLOCK
   	input 		          		ADC_CLK_10,
   `endif
   	//////////// CLOCK 1: 3.3-V LVTTL //////////
   `ifdef ENABLE_CLOCK1
   	input 		          		MAX10_CLK1_50,
   `endif
   	//////////// CLOCK 2: 3.3-V LVTTL //////////
   `ifdef ENABLE_CLOCK2
   	input 		          		MAX10_CLK2_50,
   `endif
    
   	//////////// SDRAM: 3.3-V LVTTL //////////
   `ifdef ENABLE_SDRAM
   	output		    [12:0]		DRAM_ADDR,
   	output		     [1:0]		DRAM_BA,
   	output		          		DRAM_CAS_N,
   	output		          		DRAM_CKE,
   	output		          		DRAM_CLK,
   	output		          		DRAM_CS_N,
   	inout 		    [15:0]		DRAM_DQ,
   	output		          		DRAM_LDQM,
   	output		          		DRAM_RAS_N,
   	output		          		DRAM_UDQM,
   	output		          		DRAM_WE_N,
   `endif
    
   	//////////// SEG7: 3.3-V LVTTL //////////
   `ifdef ENABLE_HEX0
   	output		     [7:0]		HEX0,
   `endif
   `ifdef ENABLE_HEX1
   	output		     [7:0]		HEX1,
   `endif
   `ifdef ENABLE_HEX2
   	output		     [7:0]		HEX2,
   `endif
   `ifdef ENABLE_HEX3
   	output		     [7:0]		HEX3,
   `endif
   `ifdef ENABLE_HEX4
   	output		     [7:0]		HEX4,
   `endif
   `ifdef ENABLE_HEX5
   	output		     [7:0]		HEX5,
   `endif
    
   	//////////// KEY: 3.3 V SCHMITT TRIGGER //////////
   `ifdef ENABLE_KEY
   	input 		     [1:0]		KEY,
   `endif
    
   	//////////// LED: 3.3-V LVTTL //////////
   `ifdef ENABLE_LED
   	output		     [9:0]		LEDR,
   `endif
    
   	//////////// SW: 3.3-V LVTTL //////////
   `ifdef ENABLE_SW
   	input 		     [9:0]		SW,
   `endif
    
   	//////////// VGA: 3.3-V LVTTL //////////
   `ifdef ENABLE_VGA
   	output		     [3:0]		VGA_B,
   	output		     [3:0]		VGA_G,
   	output		          		VGA_HS,
   	output		     [3:0]		VGA_R,
   	output		          		VGA_VS,
   `endif
    
   	//////////// Accelerometer: 3.3-V LVTTL //////////
   `ifdef ENABLE_ACCELEROMETER
   	output		          		GSENSOR_CS_N,
   	input 		     [2:1]		GSENSOR_INT,
   	output		          		GSENSOR_SCLK,
   	inout 		          		GSENSOR_SDI,
   	inout 		          		GSENSOR_SDO,
   `endif
    
   	//////////// Arduino: 3.3-V LVTTL //////////
   `ifdef ENABLE_ARDUINO
   	inout 		    [15:0]		ARDUINO_IO,
   	inout 		          		ARDUINO_RESET_N,
   `endif
    
   	//////////// GPIO, GPIO connect to GPIO Default: 3.3-V LVTTL //////////
   `ifdef ENABLE_GPIO
   	inout 		    [35:0]		GPIO
   `endif
   );
 
 
   //=======================================================
   //  REG/WIRE declarations
   //=======================================================
   
   // --- altpll ---
   logic        areset;
   logic        inclk0;
   logic        c0;
   logic        c1;
   logic        locked;
   
   // --- spi_phy ---
   logic        rst_ni;
   logic        clk_i;
   logic        spi_clk;
   
   logic        req_i;
   logic        rw_ni;
   logic [5:0]  addr_i;
   logic [7:0]  wr_data_i;
   logic        ack_o;
   logic [7:0]  rd_data_o;
   
   logic        spi_cs_no;
   logic        spi_clk_o;
   logic        spi_data_o;
   logic        spi_data_i;
   logic        spi_oe_o;
   
   // --- adxl345_controller ---
   logic [7:0]  led_o;
   
   
   //=======================================================
   //  Structural coding
   //=======================================================
   
   // --- altpll ---
   assign areset  = ~KEY[0];
   assign inclk0  = MAX10_CLK1_50;
   assign rst_ni  = locked & KEY[0];
   assign clk_i   = c0;
   assign spi_clk = c1;
   
   // --- SPI tribuffer ---
   assign GSENSOR_SDI  = spi_oe_o ? spi_data_o : 1'bz;
   assign spi_data_i   = GSENSOR_SDI;
   assign GSENSOR_CS_N = spi_cs_no;
   assign GSENSOR_SCLK = spi_clk_o;
   
   // --- LED ---
   assign LEDR[7:0] = led_o;
   assign LEDR[9:8] = 2'b00;
   
   // --- adxl345_controller ---
   adxl345_controller adxl345_ctrl_inst (
                                     .clk_i      ( clk_i     ),
                                     .rst_ni     ( rst_ni    ),
                                     .key_ni     ( KEY[1]    ),
                                     .sw_i       ( SW[5:0]   ),
                                     .ack_i      ( ack_o     ),
                                     .rd_data_i  ( rd_data_o ),
                                     .req_o      ( req_i     ),
                                     .rw_no      ( rw_ni     ),
                                     .addr_o     ( addr_i    ),
                                     .wr_data_o  ( wr_data_i ),
                                     .led_o      ( led_o     )
                                     );
   
   alt_pll	alt_pll_inst (
	                       .areset ( areset ),
	                       .inclk0 ( inclk0 ),
	                       .c0     ( c0     ),
	                       .c1     ( c1     ),
	                       .locked ( locked )
	                       );
   
   spi_phy spi_phy_inst  (
                          .rst_ni     ( rst_ni     ),
                          .clk_i      ( clk_i      ),
                          .spi_clk_i  ( spi_clk    ),
                          .req_i      ( req_i      ),
                          .rw_ni      ( rw_ni      ),
                          .addr_i     ( addr_i     ),
                          .wr_data_i  ( wr_data_i  ),
                          .ack_o      ( ack_o      ),
                          .rd_data_o  ( rd_data_o  ),
                          .spi_cs_no  ( spi_cs_no  ),
                          .spi_clk_o  ( spi_clk_o  ),
                          .spi_data_o ( spi_data_o ),
                          .spi_data_i ( spi_data_i ),
                          .spi_oe_o   ( spi_oe_o   )
                          );
   
endmodule : DE10_LITE_Golden_Top
