/*
 * This source file was generated by the Gradle 'init' task
 */

public class App {
    public static void main(String[] args) {
        for(String arg : args)
            System.out.print(arg + " ");
    }
}
