#+title: Seminar Psiho-Pedagogie - 23 Noiembrie 2023

- Pentru portofoliu, studiul de caz se poate face pe caz fictiv sau pe caz de prieten din copilărie dacă elevul pentru care am realizat portofoliul nu dorește să împărtășească o perioadă în care a demonstrat comportamente negative
- Studiul de caz se realizează din perspectiva dirigintelui
- Studiul de caz trebuie să aibă 2-3 pagini

* Etapa 1 - Date despre subiect
Elevul M.I. are vârsta de 13 ani, și este născut în 9 Ianuarie 2010. Se află în clasa a VII-a. Provine din județul Brasov, orașul Brașov, Școala Gimnazială Nr. 2. Locuința sa se află tot în orașul Brașov.
* Etapa 2 - Prezentarea subiectului (5-10 rânduri)
Elevul M.I. provine dintr-o familie obijnuită, alcatuită din cei doi parinți și cei doi copii: M.I și fratele său în vârsta de un an. Elevul trăiește alături de persoanele menționate, dar și de bunicii materni care îi oferă îngrijire în perioadele în care părinții nu sunt acasă sau au programul de la serviciu încărcat. Programul elevului este unul objnuit: în general termină activitățiile școlare la ora 14:00, merge de două ori pe săptămână la Karate și în fiecare zi a săptămânii, mai puțin Duminica, dedică 4-5 ore pentru realizarea temelor.
Elevul M.I. este pasionat de tot ce ține de arhitectura clădirilor care îl înconjoară. Părinții cunosc pasiunea elevului, dar consideră că școala este primordiară, iar este visător.
* Etapa 3 - Carențele educative ale subiectului (10-15 rânduri)
De câteva luni, doamna dirigintă a elevului M.I. o telefonează constant pe mama acestuia și îi povestește despre noile sale comportamente. Mama a arătat interes față de situația copilului și a promis că va interveni, dar nu au existat schimbări.
Elevul M.I. intră la ore la 10-15 minute după terminarea pauzei, nu prea este interesat să participe la activitate.
În schimb, distrage atenția colegilor și profesorilor cu comportamente negative: Râde - deși nu este cazul, intervine peste profesori - dar în mod insistent, lovește cu piciorul în bancă ostentativ și își deranjează colega de bancă.
De câteva săptămâni, doamna dirigintă a sesizat că îi jignește pe colegi, și chiar a participat la o bătaie în curtea școlii.
Sancțiunea a fost reprezentată de trei zile de exmatriculare. Acasă elevul a fost pedepsit prin eliminarea dispozitivelor digitale, prin evitarea de a-l integra pe elev în activități de familie, dar concret nu au existat discuții cu acesta despre comportamentele sale.
De la un timp, tatăl elevului este nevoit să plece de luni până vineri în interes de serviciu într-o altă localitate la 200km depărtare de locuința sa. Prin urmare, în timpul săptămânii, elevul se află doar cu mama, care îi oferă îngrijire și timp îndelungat fratelui de un an. Bunicii materni sunt prezenți, dar bunica oferă ajutor constant mamei, și bunicul, deși este dornic să petreacă timp cu elevul M.I., elevul nu-l acceptă, simțind absența tatălui destul de acut. Cu toate acestea, bunicul sesizează că elevul este obosit de o vreme-ncoace, este încercănat mereu, nu mai are poftă de mâncare și este irascibil. Bunicul chiar a avut o discuție cu tatăl elevului în care i-a precizat schimbările pe care le-a sesizat și i-a propous să țină legătura puțin mai des cu elevul, mai ales că cei doi - tatăl și fiul - sunt foarte apropiați.
* Etapa 4 - Ipoteze și obiective (5-10 rânduri)
Pornind de la presupunerea că prezența fratelui mai mic în familie și absența tatălui în cursul săptămânii au condus la comportamentul lui M.I. De asemenea, timpul îndelungat petrecut în fiecare zi realizând teme au afectat schimbarea elevului.
Formulăm următoarele ipoteze:
1. Dacă mama ar oferi mai multă atenție elevului M.I., comportamentul acestuia s-ar schimba în bine.
2. Daca tatăl ar găsi modalități de comunicare cu elevul M.I. mai des, atunci când este plecat, s-ar observa o îmbunătățire a comportamentului acestuia.
3. Dacă părinții elevului M.I. ar pune accent și pe pasiunea acestuia, și nu numai pe activitățiile școlare, elevul M.I. ar experimenta starea de bine și diminuarea comportamentelor negative.
Pornind de la ipotezele menționate, obiectivele pe termen scurt și lung sunt următoarele:
1. Obiective pe termen scurt:
   1. Identificarea unor modalități prin care mama să poată dedica mai mult timp elevului.
   2. Stabilirea unui program sau al unui obicei prin care elevul să țină legătura cu tatăl său când acesta este plecat.
   3. Identificarea nevoilor elevului cu privire la activitatea școlară și la pasiunea sa.
2. Obiective pe termen lung:
   1. Reintegrarea elevului M.I. în colectivul clasei
   2. Stabilirea unui echilibru între viața de familie a elevului, activitățiile școlare și pasiunile sale
* Etapa 5 - Planul de intervenție (se stabilește în funcție de ipotezele și obiectivele formulate - 5-10 rânduri)
Planul de intervenție debutează cu o discuție a cadrului didactic (C.D.) cu mama elevului, acesta sesizând că posibila cauză a comportamentului elevului este reprezentată de atenția oferită fratelui mai mic de către mamă.
Din discuție, au ieșit următoarele concluzii:
- Mama se simte depășită de situație deși are ajutorul din partea bunicii elevului, nu are curajul să îl lase pe copilul său mai mic doar în grija acestuia. Se plânge de absența soțului care este plecat în interese de serviciu, pe care îl înțelege, dar totuși îl blamează. Dirigintele constată o oarecare inconstanță a mamei în ceea ce spune dar și în reacții. Îi propune mamei să găsească timp și curaj pentru a îl lăsa pe copilul cel mic în grija bunicii măcar o oră pe zi, timp în care să se ocupe doar de elevul M.I.
În acord cu ipoteza a doua, C.D. are o discuție cu tatăl elevului explicându-i acestuia cu răbdare și pe un ton corespunzător ce schimbări a sesizat la copilul său. Tatăl menționează că este nevoit să rămână la acest loc de muncă pentru a asigura toate nevoile financiare ale familiei, dar în același timp recunoaște că este pasionat de domeniul său. Dirigintele înțelege situația tatălui, îi prezintă consecințele pe termen scurt și lung, și îi propune să își creeze un program de comunicare cu elevul. Dacă își va stabili intervale relativ fixe în funcție de orarul său și al elevului, acesta se va obijnui cu idea că tatăl său este prezent, se interesează de starea lui și nu se va mai simți singur și abandonat. C.D. îi sugerează părintelui necesitatea unei oarecare discipline în a comunica cu copilul său
Planul de intervenție presupune și o discuție cu ambii părinți în acord cu ipoteza a 3-a. C.D. le semnalează acestora importanța de a accentua și pasiunea sa pentru arhitectură. Ei consideră că din statulul de diriginte, dacă atrage atenția asupra echilibrului dintre școală și pasiune, părinții vor fi mai maleabili și mai indulgenți cu elevul M.I.
Toate aceste intervenții au avut loc ca urmare a discțiilor pe care C.D. le-a avut cu elevul M.I. Din acele discuții, a dedus faptul că noile comportamente sunt cauzate mai degrabă de lipsa atenției din partea familiei și nu de dezinteresul elevului față de școală. Elevul a precizat că singurul membru al familiei care prezintă interes pentru el este bunicul, și tot odată a spus că "bunicul nu e tata"
* Etapa 6 - Ipoteze alternative (din perspectiva C.D. - 5-10 rânduri)
În cazul în care planul de intervenție nu va avea succes, atunci îmi propun să-i direcționez pe părinți către consilierul școlar. O altă alternativă ar fi reprezentată de realizarea unor ateliere pentru părinți cu scopul de ai ajuta să gestioneze mai bine responsabilitățile parentale.
* Etapa 7 - Rezultatele obținute (5-10 rânduri)
La scurt timp după discuțiile menționate în planul de intervenție, părinții au luat măsuri și s-a observat o îmbunătățire în comportamentul elevului dar și în starea sa generală.
* Etapa 8 - Concluzii
S-a constatat că lipsa de atenție oferită elevului i-a afectat calitățiile școlare dar și relația cu ceilalți colegi. Părinții au înțeles ulterior importanța de a acționa prompt și de al ajuta pe copil să se simtă important și valoros. Astfel, au contribuit la reintegrarea acestuia în colectiv și la găsirea unui echilibru între activitățiile de familie, cele școlare și pasiunile sale.
* Etapa 9 - Recomandări
Familiei i se recomandă inițierea unor discuții mai frecvente cu privire la starea elevului și evitarea suportării unor consecințe dacă comportamentul elevului este justificat (se exclude agresivitatea de orice fel).
Elevului i se recomandă să accepte ajutorul bunicului pe viitor, chiar dacă acesta nu poate ține locul tatălui.
Școlii i se recomandă acordarea unei atenții sporite atât elevului M.I. în continuare, cât și altor elevi care se confruntă cu situații similare
